import os

SERVER_PORT = os.getenv("SERVER_PORT", 9000)
SERVER_HOST = os.getenv("SERVER_HOST", "127.0.0.1")

VEHICLE_SERVER_PORT = os.getenv("VEHICLE_SERVER_PORT", 8080)
VEHICLE_SERVER_HOST = os.getenv("VEHICLE_SERVER_HOST", "127.0.0.1")

MONGODB_PORT = os.getenv("MONGODB_PORT", 27017)
MONGODB_HOST = os.getenv("MONGODB_HOST", "127.0.0.1")
MONGODB_DB_NAME = os.getenv("MONGODB_DB_NAME", "vehicle")

VEHICLE_CONNECTION_URL = f"ws://{VEHICLE_SERVER_HOST}:{VEHICLE_SERVER_PORT}"

MONGODB_CONNECTION_URL = f"mongodb://{MONGODB_HOST}:{MONGODB_PORT}"
